version: '3.8'
services:
  backend:
    build: ./backend
    container_name: mtg-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: mtg-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
